//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VanLian_OMSEntities : DbContext
    {
        public VanLian_OMSEntities()
            : base("name=VanLian_OMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<oms_open_tt_PurchaseOrder> oms_open_tt_PurchaseOrder { get; set; }
        public virtual DbSet<oms_open_tt_PurchaseOrderItem> oms_open_tt_PurchaseOrderItem { get; set; }
        public virtual DbSet<oms_open_vd_PurchaseOrderStatus> oms_open_vd_PurchaseOrderStatus { get; set; }
        public virtual DbSet<oms_ttl_SalesOrderPurchaseLog> oms_ttl_SalesOrderPurchaseLog { get; set; }
        public virtual DbSet<oms_tt_SalesOrderHouseholder> oms_tt_SalesOrderHouseholder { get; set; }
        public virtual DbSet<oms_tt_SalesOrderItem> oms_tt_SalesOrderItem { get; set; }
        public virtual DbSet<oms_tt_SettlementOrder> oms_tt_SettlementOrder { get; set; }
        public virtual DbSet<oms_tt_SettlementOrderItem> oms_tt_SettlementOrderItem { get; set; }
        public virtual DbSet<oms_tt_WarehouseIO> oms_tt_WarehouseIO { get; set; }
        public virtual DbSet<oms_tt_WarehouseIOItem> oms_tt_WarehouseIOItem { get; set; }
        public virtual DbSet<oms_tt_WarehouseIOTransport> oms_tt_WarehouseIOTransport { get; set; }
        public virtual DbSet<oms_ttl_ReviewRuleLog> oms_ttl_ReviewRuleLog { get; set; }
        public virtual DbSet<oms_ttl_SalesOrderItem_StandardLog> oms_ttl_SalesOrderItem_StandardLog { get; set; }
        public virtual DbSet<oms_open_vd_RequestProcessStatus> oms_open_vd_RequestProcessStatus { get; set; }
        public virtual DbSet<oms_open_vd_ShipmentOrderStatus> oms_open_vd_ShipmentOrderStatus { get; set; }
        public virtual DbSet<oms_open_vd_ShopOrderStatus> oms_open_vd_ShopOrderStatus { get; set; }
        public virtual DbSet<oms_open_vd_TaskStatus> oms_open_vd_TaskStatus { get; set; }
        public virtual DbSet<oms_open_vd_TaskType> oms_open_vd_TaskType { get; set; }
        public virtual DbSet<oms_open_vl_Request> oms_open_vl_Request { get; set; }
        public virtual DbSet<oms_open_vm_APP> oms_open_vm_APP { get; set; }
        public virtual DbSet<oms_open_vm_ISV> oms_open_vm_ISV { get; set; }
        public virtual DbSet<oms_open_vm_Material> oms_open_vm_Material { get; set; }
        public virtual DbSet<oms_open_vt_BillOrder> oms_open_vt_BillOrder { get; set; }
        public virtual DbSet<oms_open_vt_BillOrderItem> oms_open_vt_BillOrderItem { get; set; }
        public virtual DbSet<oms_open_vt_MatchingMaterialList> oms_open_vt_MatchingMaterialList { get; set; }
        public virtual DbSet<oms_open_vt_MatchingSupplierList> oms_open_vt_MatchingSupplierList { get; set; }
        public virtual DbSet<oms_open_vt_PurchaseOrder> oms_open_vt_PurchaseOrder { get; set; }
        public virtual DbSet<oms_open_vt_PurchaseOrderItem> oms_open_vt_PurchaseOrderItem { get; set; }
        public virtual DbSet<oms_open_vt_PurchaseOrderTradeInfo> oms_open_vt_PurchaseOrderTradeInfo { get; set; }
        public virtual DbSet<oms_open_vt_PurchaseReturnOrder> oms_open_vt_PurchaseReturnOrder { get; set; }
        public virtual DbSet<oms_open_vt_PurchaseReturnOrderItem> oms_open_vt_PurchaseReturnOrderItem { get; set; }
        public virtual DbSet<oms_open_vt_SettlementOrder> oms_open_vt_SettlementOrder { get; set; }
        public virtual DbSet<oms_open_vt_SettlementOrderItem> oms_open_vt_SettlementOrderItem { get; set; }
        public virtual DbSet<oms_open_vt_ShipmentOrder> oms_open_vt_ShipmentOrder { get; set; }
        public virtual DbSet<oms_open_vt_ShipmentOrderItem> oms_open_vt_ShipmentOrderItem { get; set; }
        public virtual DbSet<oms_open_vt_ShoppingOrder> oms_open_vt_ShoppingOrder { get; set; }
        public virtual DbSet<oms_open_vt_ShoppingOrderItem> oms_open_vt_ShoppingOrderItem { get; set; }
        public virtual DbSet<oms_open_vt_Task> oms_open_vt_Task { get; set; }
        public virtual DbSet<oms_va_Biz_InPa> oms_va_Biz_InPa { get; set; }
        public virtual DbSet<oms_va_Inventory> oms_va_Inventory { get; set; }
        public virtual DbSet<oms_vd_BillOrderStatus> oms_vd_BillOrderStatus { get; set; }
        public virtual DbSet<oms_vd_DeliveryMode> oms_vd_DeliveryMode { get; set; }
        public virtual DbSet<oms_vd_DeliveryOrderStatus> oms_vd_DeliveryOrderStatus { get; set; }
        public virtual DbSet<oms_vd_InventoryType> oms_vd_InventoryType { get; set; }
        public virtual DbSet<oms_vd_LinkDataType> oms_vd_LinkDataType { get; set; }
        public virtual DbSet<oms_vd_MaterialType> oms_vd_MaterialType { get; set; }
        public virtual DbSet<oms_vd_ProjectType> oms_vd_ProjectType { get; set; }
        public virtual DbSet<oms_vd_PurchaseStatus> oms_vd_PurchaseStatus { get; set; }
        public virtual DbSet<oms_vd_PurchaseType> oms_vd_PurchaseType { get; set; }
        public virtual DbSet<oms_vd_ReturnMode> oms_vd_ReturnMode { get; set; }
        public virtual DbSet<oms_vd_ReturnOrderStatus> oms_vd_ReturnOrderStatus { get; set; }
        public virtual DbSet<oms_vd_ReviewResult> oms_vd_ReviewResult { get; set; }
        public virtual DbSet<oms_vd_ReviewRuleType> oms_vd_ReviewRuleType { get; set; }
        public virtual DbSet<oms_vd_ReviewStatus> oms_vd_ReviewStatus { get; set; }
        public virtual DbSet<oms_vd_SalesOrderItemStatus> oms_vd_SalesOrderItemStatus { get; set; }
        public virtual DbSet<oms_vd_SalesOrderPurchaseStatus> oms_vd_SalesOrderPurchaseStatus { get; set; }
        public virtual DbSet<oms_vd_SalesOrderStatus> oms_vd_SalesOrderStatus { get; set; }
        public virtual DbSet<oms_vd_SettlementOrderStatus> oms_vd_SettlementOrderStatus { get; set; }
        public virtual DbSet<oms_vd_SupplierType> oms_vd_SupplierType { get; set; }
        public virtual DbSet<oms_vd_SupplyType> oms_vd_SupplyType { get; set; }
        public virtual DbSet<oms_vd_TransFeeSettlementsMode> oms_vd_TransFeeSettlementsMode { get; set; }
        public virtual DbSet<oms_vd_TransMode> oms_vd_TransMode { get; set; }
        public virtual DbSet<oms_vd_Unit> oms_vd_Unit { get; set; }
        public virtual DbSet<oms_vd_WarehouseIOStatus> oms_vd_WarehouseIOStatus { get; set; }
        public virtual DbSet<oms_vd_WarehouseIOType> oms_vd_WarehouseIOType { get; set; }
        public virtual DbSet<oms_vd_WarehouseType> oms_vd_WarehouseType { get; set; }
        public virtual DbSet<oms_vl_InterfaceFeedback_ConfirmReturnLog> oms_vl_InterfaceFeedback_ConfirmReturnLog { get; set; }
        public virtual DbSet<oms_vl_InterfaceFeedback_CustomizedOrderLog> oms_vl_InterfaceFeedback_CustomizedOrderLog { get; set; }
        public virtual DbSet<oms_vl_InterfaceFeedBack_DeliveryOrderLog> oms_vl_InterfaceFeedBack_DeliveryOrderLog { get; set; }
        public virtual DbSet<oms_vl_InterfaceFeedback_LackOfMaterialLog> oms_vl_InterfaceFeedback_LackOfMaterialLog { get; set; }
        public virtual DbSet<oms_vl_InterfaceFeedback_RejectReturnLog> oms_vl_InterfaceFeedback_RejectReturnLog { get; set; }
        public virtual DbSet<oms_vl_log> oms_vl_log { get; set; }
        public virtual DbSet<oms_vl_log_lite> oms_vl_log_lite { get; set; }
        public virtual DbSet<oms_vm_ConsGroupLeader> oms_vm_ConsGroupLeader { get; set; }
        public virtual DbSet<oms_vm_ConstructionTeam> oms_vm_ConstructionTeam { get; set; }
        public virtual DbSet<oms_vm_Designer> oms_vm_Designer { get; set; }
        public virtual DbSet<oms_vm_Material> oms_vm_Material { get; set; }
        public virtual DbSet<oms_vm_Operator> oms_vm_Operator { get; set; }
        public virtual DbSet<oms_vm_OperatorRole> oms_vm_OperatorRole { get; set; }
        public virtual DbSet<oms_vm_Purview> oms_vm_Purview { get; set; }
        public virtual DbSet<oms_vm_QAManager> oms_vm_QAManager { get; set; }
        public virtual DbSet<oms_vm_ReviewRule> oms_vm_ReviewRule { get; set; }
        public virtual DbSet<oms_vm_ReviewRuleItem> oms_vm_ReviewRuleItem { get; set; }
        public virtual DbSet<oms_vm_ReviewRuleItem_MyExamine> oms_vm_ReviewRuleItem_MyExamine { get; set; }
        public virtual DbSet<oms_vm_Supplier> oms_vm_Supplier { get; set; }
        public virtual DbSet<oms_vm_SupplyPrice> oms_vm_SupplyPrice { get; set; }
        public virtual DbSet<oms_vm_tms_City> oms_vm_tms_City { get; set; }
        public virtual DbSet<oms_vm_tms_CityBV> oms_vm_tms_CityBV { get; set; }
        public virtual DbSet<oms_vm_Warehouse> oms_vm_Warehouse { get; set; }
        public virtual DbSet<oms_vm_WarehouseWorker> oms_vm_WarehouseWorker { get; set; }
        public virtual DbSet<oms_vs_Company> oms_vs_Company { get; set; }
        public virtual DbSet<oms_vs_Func> oms_vs_Func { get; set; }
        public virtual DbSet<oms_vs_FuncGroup> oms_vs_FuncGroup { get; set; }
        public virtual DbSet<oms_vs_SubFunc> oms_vs_SubFunc { get; set; }
        public virtual DbSet<oms_vt_BillOrder> oms_vt_BillOrder { get; set; }
        public virtual DbSet<oms_vt_BillOrderItem> oms_vt_BillOrderItem { get; set; }
        public virtual DbSet<oms_vt_DeliveryOrder> oms_vt_DeliveryOrder { get; set; }
        public virtual DbSet<oms_vt_DeliveryOrderItem> oms_vt_DeliveryOrderItem { get; set; }
        public virtual DbSet<oms_vt_DeliveryOrderTransport> oms_vt_DeliveryOrderTransport { get; set; }
        public virtual DbSet<oms_vt_interface2oms_2_21_SalesOrder> oms_vt_interface2oms_2_21_SalesOrder { get; set; }
        public virtual DbSet<oms_vt_interface2oms_2_21_SalesOrderItem> oms_vt_interface2oms_2_21_SalesOrderItem { get; set; }
        public virtual DbSet<oms_vt_interface2oms_2_24_ReturnOrder> oms_vt_interface2oms_2_24_ReturnOrder { get; set; }
        public virtual DbSet<oms_vt_interface2oms_2_24_ReturnOrderItem> oms_vt_interface2oms_2_24_ReturnOrderItem { get; set; }
        public virtual DbSet<oms_vt_Inventory_Supplier> oms_vt_Inventory_Supplier { get; set; }
        public virtual DbSet<oms_vt_Purchase_ConfirmWarehouseIOItem> oms_vt_Purchase_ConfirmWarehouseIOItem { get; set; }
        public virtual DbSet<oms_vt_Purchase_CustomerPurchaseOrderItem> oms_vt_Purchase_CustomerPurchaseOrderItem { get; set; }
        public virtual DbSet<oms_vt_Purchase_LessWarehousedFC> oms_vt_Purchase_LessWarehousedFC { get; set; }
        public virtual DbSet<oms_vt_Purchase_MaterialAndSupplier> oms_vt_Purchase_MaterialAndSupplier { get; set; }
        public virtual DbSet<oms_vt_Purchase_SalesOrderInfoAndItem> oms_vt_Purchase_SalesOrderInfoAndItem { get; set; }
        public virtual DbSet<oms_vt_Purchase_SalesOrderItem> oms_vt_Purchase_SalesOrderItem { get; set; }
        public virtual DbSet<oms_vt_Purchase_SalesOrderItemAndSupplierID> oms_vt_Purchase_SalesOrderItemAndSupplierID { get; set; }
        public virtual DbSet<oms_vt_Purchase_SelectPurchaseOrder> oms_vt_Purchase_SelectPurchaseOrder { get; set; }
        public virtual DbSet<oms_vt_Purchase_WarehouseIO> oms_vt_Purchase_WarehouseIO { get; set; }
        public virtual DbSet<oms_vt_PurchaseOrder> oms_vt_PurchaseOrder { get; set; }
        public virtual DbSet<oms_vt_PurchaseOrderItem> oms_vt_PurchaseOrderItem { get; set; }
        public virtual DbSet<oms_vt_PurchaseOrderItem_Delivery> oms_vt_PurchaseOrderItem_Delivery { get; set; }
        public virtual DbSet<oms_vt_PurchaseOrderItem_InventoryOrder> oms_vt_PurchaseOrderItem_InventoryOrder { get; set; }
        public virtual DbSet<oms_vt_ReturnOrder> oms_vt_ReturnOrder { get; set; }
        public virtual DbSet<oms_vt_ReturnOrder_SalesOrderInfo> oms_vt_ReturnOrder_SalesOrderInfo { get; set; }
        public virtual DbSet<oms_vt_ReturnOrder_SalesOrderItem> oms_vt_ReturnOrder_SalesOrderItem { get; set; }
        public virtual DbSet<oms_vt_ReturnOrderItem> oms_vt_ReturnOrderItem { get; set; }
        public virtual DbSet<oms_vt_SalesOrder> oms_vt_SalesOrder { get; set; }
        public virtual DbSet<oms_vt_SalesOrderContract> oms_vt_SalesOrderContract { get; set; }
        public virtual DbSet<oms_vt_SalesOrderDelivery> oms_vt_SalesOrderDelivery { get; set; }
        public virtual DbSet<oms_vt_SalesOrderHouseholder> oms_vt_SalesOrderHouseholder { get; set; }
        public virtual DbSet<oms_vt_SalesOrderInfo> oms_vt_SalesOrderInfo { get; set; }
        public virtual DbSet<oms_vt_SalesOrderItem> oms_vt_SalesOrderItem { get; set; }
        public virtual DbSet<oms_vt_SalesOrderReview> oms_vt_SalesOrderReview { get; set; }
        public virtual DbSet<oms_vt_SettlementOrder> oms_vt_SettlementOrder { get; set; }
        public virtual DbSet<oms_vt_SettlementOrderItem> oms_vt_SettlementOrderItem { get; set; }
        public virtual DbSet<oms_vt_Supplier_DeliveryOrder> oms_vt_Supplier_DeliveryOrder { get; set; }
        public virtual DbSet<oms_vt_WarehouseIO> oms_vt_WarehouseIO { get; set; }
        public virtual DbSet<oms_vt_WarehouseIOItem> oms_vt_WarehouseIOItem { get; set; }
        public virtual DbSet<oms_vt_wms_Inventory> oms_vt_wms_Inventory { get; set; }
        public virtual DbSet<oms_vt_wms_Inventory_from_with_wms_storage> oms_vt_wms_Inventory_from_with_wms_storage { get; set; }
        public virtual DbSet<oms_vt_wms_InventoryBatch_from_with_wms_storage> oms_vt_wms_InventoryBatch_from_with_wms_storage { get; set; }
        public virtual DbSet<oms_vt_wms_InventoryItem> oms_vt_wms_InventoryItem { get; set; }
        public virtual DbSet<oms_vtl_ReviewRuleLog> oms_vtl_ReviewRuleLog { get; set; }
        public virtual DbSet<oms_vtl_SalesOrderPurchaseLog> oms_vtl_SalesOrderPurchaseLog { get; set; }
        public virtual DbSet<oms_vx_xhelper_sys_Globe> oms_vx_xhelper_sys_Globe { get; set; }
        public virtual DbSet<wms订单单价获取用> wms订单单价获取用 { get; set; }
        public virtual DbSet<oms_tm_Purview> oms_tm_Purview { get; set; }
        public virtual DbSet<oms_tm_QAManager> oms_tm_QAManager { get; set; }
        public virtual DbSet<oms_tm_ReviewRule> oms_tm_ReviewRule { get; set; }
        public virtual DbSet<oms_tm_ReviewRuleItem> oms_tm_ReviewRuleItem { get; set; }
        public virtual DbSet<oms_tm_ReviewRuleItem_MyExamine> oms_tm_ReviewRuleItem_MyExamine { get; set; }
        public virtual DbSet<oms_tm_Supplier> oms_tm_Supplier { get; set; }
        public virtual DbSet<oms_tm_SupplyPrice> oms_tm_SupplyPrice { get; set; }
        public virtual DbSet<oms_tm_Warehouse> oms_tm_Warehouse { get; set; }
        public virtual DbSet<oms_tm_WarehouseWorker> oms_tm_WarehouseWorker { get; set; }
        public virtual DbSet<oms_ts_Company> oms_ts_Company { get; set; }
        public virtual DbSet<oms_ts_Func> oms_ts_Func { get; set; }
        public virtual DbSet<oms_ts_FuncGroup> oms_ts_FuncGroup { get; set; }
        public virtual DbSet<oms_ts_SubFunc> oms_ts_SubFunc { get; set; }
        public virtual DbSet<oms_tt_BillOrder> oms_tt_BillOrder { get; set; }
        public virtual DbSet<oms_tt_BillOrderItem> oms_tt_BillOrderItem { get; set; }
        public virtual DbSet<oms_tt_DeliveryOrder> oms_tt_DeliveryOrder { get; set; }
        public virtual DbSet<oms_tt_DeliveryOrderItem> oms_tt_DeliveryOrderItem { get; set; }
        public virtual DbSet<oms_tt_DeliveryOrderTransport> oms_tt_DeliveryOrderTransport { get; set; }
        public virtual DbSet<oms_tt_PurchaseOrder> oms_tt_PurchaseOrder { get; set; }
        public virtual DbSet<oms_td_WarehouseType> oms_td_WarehouseType { get; set; }
        public virtual DbSet<oms_tl_log> oms_tl_log { get; set; }
        public virtual DbSet<oms_tm_ConsGroupLeader> oms_tm_ConsGroupLeader { get; set; }
        public virtual DbSet<oms_tm_ConstructionTeam> oms_tm_ConstructionTeam { get; set; }
        public virtual DbSet<oms_tm_Designer> oms_tm_Designer { get; set; }
        public virtual DbSet<oms_tm_Material> oms_tm_Material { get; set; }
        public virtual DbSet<oms_tm_Operator> oms_tm_Operator { get; set; }
        public virtual DbSet<oms_tm_OperatorRole> oms_tm_OperatorRole { get; set; }
        public virtual DbSet<oms_tt_PurchaseOrderItem> oms_tt_PurchaseOrderItem { get; set; }
        public virtual DbSet<oms_tt_ReturnOrder> oms_tt_ReturnOrder { get; set; }
        public virtual DbSet<oms_tt_ReturnOrderItem> oms_tt_ReturnOrderItem { get; set; }
        public virtual DbSet<oms_tt_ReturnOrderTransport> oms_tt_ReturnOrderTransport { get; set; }
        public virtual DbSet<oms_tt_SalesOrder> oms_tt_SalesOrder { get; set; }
        public virtual DbSet<oms_tt_SalesOrderContract> oms_tt_SalesOrderContract { get; set; }
        public virtual DbSet<oms_tt_SalesOrderDelivery> oms_tt_SalesOrderDelivery { get; set; }
        public virtual DbSet<oms_ta_Biz_InPa> oms_ta_Biz_InPa { get; set; }
        public virtual DbSet<oms_ta_Inventory> oms_ta_Inventory { get; set; }
        public virtual DbSet<oms_td_BillOrderStatus> oms_td_BillOrderStatus { get; set; }
        public virtual DbSet<oms_td_DeliveryMode> oms_td_DeliveryMode { get; set; }
        public virtual DbSet<oms_td_DeliveryOrderStatus> oms_td_DeliveryOrderStatus { get; set; }
        public virtual DbSet<oms_td_InventoryType> oms_td_InventoryType { get; set; }
        public virtual DbSet<oms_td_LinkDataType> oms_td_LinkDataType { get; set; }
        public virtual DbSet<oms_td_MaterialType> oms_td_MaterialType { get; set; }
        public virtual DbSet<oms_td_ProjectType> oms_td_ProjectType { get; set; }
        public virtual DbSet<oms_td_PurchaseStatus> oms_td_PurchaseStatus { get; set; }
        public virtual DbSet<oms_td_PurchaseType> oms_td_PurchaseType { get; set; }
        public virtual DbSet<oms_td_ReturnMode> oms_td_ReturnMode { get; set; }
        public virtual DbSet<oms_td_ReturnOrderStatus> oms_td_ReturnOrderStatus { get; set; }
        public virtual DbSet<oms_td_ReviewResult> oms_td_ReviewResult { get; set; }
        public virtual DbSet<oms_td_ReviewRuleType> oms_td_ReviewRuleType { get; set; }
        public virtual DbSet<oms_td_ReviewStatus> oms_td_ReviewStatus { get; set; }
        public virtual DbSet<oms_td_SalesOrderItemStatus> oms_td_SalesOrderItemStatus { get; set; }
        public virtual DbSet<oms_td_SalesOrderPurchaseStatus> oms_td_SalesOrderPurchaseStatus { get; set; }
        public virtual DbSet<oms_td_SalesOrderStatus> oms_td_SalesOrderStatus { get; set; }
        public virtual DbSet<oms_td_SettlementOrderStatus> oms_td_SettlementOrderStatus { get; set; }
        public virtual DbSet<oms_td_SupplierType> oms_td_SupplierType { get; set; }
        public virtual DbSet<oms_td_SupplyType> oms_td_SupplyType { get; set; }
        public virtual DbSet<oms_td_TransFeeSettlementsMode> oms_td_TransFeeSettlementsMode { get; set; }
        public virtual DbSet<oms_td_TransMode> oms_td_TransMode { get; set; }
        public virtual DbSet<oms_td_Unit> oms_td_Unit { get; set; }
        public virtual DbSet<oms_td_WarehouseIOStatus> oms_td_WarehouseIOStatus { get; set; }
        public virtual DbSet<oms_td_WarehouseIOType> oms_td_WarehouseIOType { get; set; }
        public virtual DbSet<oms_open_td_PurchaseOrderStatus> oms_open_td_PurchaseOrderStatus { get; set; }
        public virtual DbSet<oms_open_td_RequestProcessStatus> oms_open_td_RequestProcessStatus { get; set; }
        public virtual DbSet<oms_open_td_ShipmentOrderStatus> oms_open_td_ShipmentOrderStatus { get; set; }
        public virtual DbSet<oms_open_td_ShopOrderStatus> oms_open_td_ShopOrderStatus { get; set; }
        public virtual DbSet<oms_open_td_TaskStatus> oms_open_td_TaskStatus { get; set; }
        public virtual DbSet<oms_open_td_TaskType> oms_open_td_TaskType { get; set; }
        public virtual DbSet<oms_open_tl_Request> oms_open_tl_Request { get; set; }
        public virtual DbSet<oms_open_tm_APP> oms_open_tm_APP { get; set; }
        public virtual DbSet<oms_open_tm_ISV> oms_open_tm_ISV { get; set; }
        public virtual DbSet<oms_open_tt_PurchaseOrderTradeInfo> oms_open_tt_PurchaseOrderTradeInfo { get; set; }
        public virtual DbSet<oms_open_tt_ShipmentOrder> oms_open_tt_ShipmentOrder { get; set; }
        public virtual DbSet<oms_open_tt_ShipmentOrderItem> oms_open_tt_ShipmentOrderItem { get; set; }
        public virtual DbSet<oms_open_tt_ShoppingOrder> oms_open_tt_ShoppingOrder { get; set; }
        public virtual DbSet<oms_open_tt_ShoppingOrderItem> oms_open_tt_ShoppingOrderItem { get; set; }
        public virtual DbSet<oms_open_tt_Task> oms_open_tt_Task { get; set; }
    }
}
