//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vl_InterfaceFeedback_CustomizedOrderLog
    {
        public System.Guid SalesOrderPurchaseLogID { get; set; }
        public System.Guid CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public System.Guid SalesOrderID { get; set; }
        public string SalesOrderCode { get; set; }
        public string OrigSalesOrderCode { get; set; }
        public Nullable<System.Guid> PurchaseOrderID { get; set; }
        public string PurchaseOrder { get; set; }
        public int SalesOrderPurchaseStatusCode { get; set; }
        public string SalesOrderPurchaseStatusName { get; set; }
        public string Memo { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public string Creater { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public string SyncVssFlag { get; set; }
        public byte SyncVssNum_Delivery { get; set; }
        public Nullable<System.DateTime> SyncVssDate_Delivery { get; set; }
    }
}
