//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_open_tt_PurchaseOrderItem
    {
        public System.Guid openPurchaseOrderItemID { get; set; }
        public System.Guid openPurchaseOrderID { get; set; }
        public System.Guid APPID { get; set; }
        public string o_id { get; set; }
        public string o_mainOrderId { get; set; }
        public string o_fee { get; set; }
        public string o_originFee { get; set; }
        public string o_paidFee { get; set; }
        public string o_shipFee { get; set; }
        public string o_itemId { get; set; }
        public string o_itemName { get; set; }
        public string o_skuId { get; set; }
        public string o_skuCode { get; set; }
        public string o_skuPrice { get; set; }
        public Nullable<long> o_quantity { get; set; }
        public Nullable<long> o_receiveQuantity { get; set; }
        public Nullable<System.DateTime> o_createdAt { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public Nullable<bool> IsMappingMissing { get; set; }
        public Nullable<System.Guid> MaterialID { get; set; }
        public Nullable<System.Guid> PurchaseOrderItemID { get; set; }
    }
}
