//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_open_vt_MatchingMaterialList
    {
        public string o_skuId { get; set; }
        public string o_skuCode { get; set; }
        public Nullable<bool> IsMappingMissing { get; set; }
        public Nullable<int> openPurchaseOrderStatusCode { get; set; }
        public string ViewID { get; set; }
        public System.Guid openPurchaseOrderID { get; set; }
    }
}
