//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_SalesOrderReview
    {
        public System.Guid SalesOrderID { get; set; }
        public System.Guid CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string SalesOrderCode { get; set; }
        public string OrigSalesOrderCode { get; set; }
        public string ContractCode { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public System.Guid WarehouseID { get; set; }
        public Nullable<int> SalesOrderMaterialType { get; set; }
        public string SalesOrderMaterialTypeName { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public string ProjectTypeName { get; set; }
        public string DesignerCode { get; set; }
        public string DesignerName { get; set; }
        public string ConsTeamCode { get; set; }
        public string ConsLeaderCode { get; set; }
        public string ConsLeaderName { get; set; }
        public string Signer { get; set; }
        public string OwnerShop { get; set; }
        public Nullable<System.DateTime> BeginWorkDate { get; set; }
        public string Memo { get; set; }
        public string HHName { get; set; }
        public string HHPhone { get; set; }
        public string HHMobilePhone { get; set; }
        public string HHAddress { get; set; }
        public string HHContacts { get; set; }
        public string HHContactPhone { get; set; }
        public Nullable<System.DateTime> ExpetDeliveryDate { get; set; }
        public Nullable<int> DeliveryMode { get; set; }
        public string DeliveryModeName { get; set; }
        public string Vehicle { get; set; }
        public string DeliveryMemo { get; set; }
        public Nullable<int> SalesOrderStatusCode { get; set; }
        public string SalesOrderStatusName { get; set; }
        public System.Guid SalesOrderItemID { get; set; }
        public System.Guid MaterialID { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string BarCode { get; set; }
        public string Model { get; set; }
        public Nullable<int> MaterialType { get; set; }
        public string MaterialTypeName { get; set; }
        public Nullable<int> SupplyType { get; set; }
        public string SupplyTypeName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ConversionQuantity { get; set; }
        public Nullable<int> ExpectDamageQuantity { get; set; }
        public int SaleableQuantity { get; set; }
        public Nullable<int> DeliveryQuantity { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string StandardDetail { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string SupplierType { get; set; }
        public Nullable<int> OOSQuantity { get; set; }
        public string DrawingsURL { get; set; }
        public int FinalQuantity { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public Nullable<bool> ReviewFinish { get; set; }
        public Nullable<bool> ReviewFinishItem { get; set; }
        public int SalesOrderItemStatusCode { get; set; }
        public string SalesOrderItemStatusName { get; set; }
        public string SubmitSource { get; set; }
        public string ProductPackage { get; set; }
    }
}
