//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_tt_ReturnOrderTransport
    {
        public System.Guid ROTransportID { get; set; }
        public System.Guid ReturnOrderID { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string LogisticsCompanyName { get; set; }
        public string DriverName { get; set; }
        public string DriverPhone { get; set; }
        public string LicencePlate { get; set; }
        public string ReturnExpressCompanyName { get; set; }
        public string ReturnExpressOrderCode { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
    }
}
