//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_tt_BillOrder
    {
        public System.Guid BillOrderID { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid SupplierID { get; set; }
        public string BillOrderCode { get; set; }
        public int MaterialType { get; set; }
        public Nullable<System.DateTime> BeforeDate { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public Nullable<int> count_poin { get; set; }
        public Nullable<int> count_poout { get; set; }
        public Nullable<int> SignVerifyCostDays_expect { get; set; }
        public Nullable<int> SignVerifyCostDays_fact { get; set; }
        public Nullable<bool> SignVerify_timeout { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string RejectReason { get; set; }
        public int BillOrderStatusCode { get; set; }
        public int TotalBillingQuantity { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<decimal> TotalPurchaseAmount { get; set; }
        public Nullable<decimal> TotalReturnAmount { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public Nullable<bool> IsSettlement { get; set; }
        public Nullable<System.Guid> CurrentReviewRuleItemID { get; set; }
        public Nullable<System.Guid> CurrentReviewSubmiter { get; set; }
        public Nullable<int> CurrentReviewStatusCode { get; set; }
        public Nullable<System.DateTime> CurrentReviewBeginTime { get; set; }
        public Nullable<bool> IsopenData { get; set; }
    }
}
