//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_SalesOrder
    {
        public System.Guid SalesOrderID { get; set; }
        public System.Guid CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string SalesOrderCode { get; set; }
        public Nullable<int> SalesOrderStatusCode { get; set; }
        public string SalesOrderStatusName { get; set; }
        public Nullable<System.Guid> OrigSalesOrderID { get; set; }
        public string OrigSalesOrderCode { get; set; }
        public string ContractCode { get; set; }
        public System.Guid WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<int> SalesOrderMaterialType { get; set; }
        public string SalesOrderMaterialTypeName { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public string ProjectTypeName { get; set; }
        public System.Guid DesignerID { get; set; }
        public string DesignerCode { get; set; }
        public string DesignerName { get; set; }
        public System.Guid ConsTeamID { get; set; }
        public string ConsTeamCode { get; set; }
        public string ConsLeaderCode { get; set; }
        public string ConsLeaderName { get; set; }
        public string Signer { get; set; }
        public string OwnerShop { get; set; }
        public Nullable<System.DateTime> BeginWorkDate { get; set; }
        public string CancelReason { get; set; }
        public string Memo { get; set; }
        public string MadeSizeMemo { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public Nullable<bool> ReviewFinish { get; set; }
        public string SubmitSource { get; set; }
    }
}
