//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_open_tt_ShoppingOrder
    {
        public System.Guid openShoppingOrderID { get; set; }
        public System.Guid APPID { get; set; }
        public System.Guid openPurchaseOrderID { get; set; }
        public string o_mainOrderId { get; set; }
        public string o_shopOrderId { get; set; }
        public Nullable<System.DateTime> o_time { get; set; }
        public Nullable<int> openShopOrderStatusCode { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public System.Guid WarehouseIOID { get; set; }
        public Nullable<System.Guid> openShipmentOrderID { get; set; }
    }
}
