//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_Purchase_MaterialAndSupplier
    {
        public System.Guid MaterialID { get; set; }
        public string BarCode { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> MaterialType { get; set; }
        public Nullable<int> SupplyType { get; set; }
        public string Model { get; set; }
        public string Unit { get; set; }
        public System.Guid SupplierID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public System.Guid CompanyID { get; set; }
    }
}
