//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_tt_SettlementOrder
    {
        public System.Guid SettlementOrderID { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid SupplierID { get; set; }
        public Nullable<System.Guid> BillOrderID { get; set; }
        public string SettlementOrderCode { get; set; }
        public int SettlementOrderStatusCode { get; set; }
        public decimal TotalBillAmount { get; set; }
        public decimal TotalSettlementAmount { get; set; }
        public decimal TotalConfirmAmount { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public Nullable<decimal> TotalIncomeAmount { get; set; }
        public Nullable<decimal> TotalPaymentAmount { get; set; }
        public Nullable<System.Guid> CurrentReviewRuleItemID { get; set; }
        public Nullable<System.Guid> CurrentReviewSubmiter { get; set; }
        public Nullable<int> CurrentReviewStatusCode { get; set; }
        public Nullable<System.DateTime> CurrentReviewBeginTime { get; set; }
    }
}
