//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_open_vt_Task
    {
        public System.Guid openTaskID { get; set; }
        public System.Guid APPID { get; set; }
        public string APPCode { get; set; }
        public string APPName { get; set; }
        public string ISVCode { get; set; }
        public string ISVName { get; set; }
        public int openTaskTypeCode { get; set; }
        public string openTaskTypeName { get; set; }
        public Nullable<System.Guid> openOrderID { get; set; }
        public int openTaskStatusCode { get; set; }
        public string openTaskStatusName { get; set; }
        public Nullable<int> openTaskNum { get; set; }
        public string openTaskResult { get; set; }
        public Nullable<System.DateTime> openTaskDate { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
    }
}
