//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_interface2oms_2_24_ReturnOrderItem
    {
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> Unit { get; set; }
        public string UnitName { get; set; }
        public string Model { get; set; }
        public string InventoryTypeCode { get; set; }
        public string InventoryTypeName { get; set; }
        public Nullable<int> ExpectQuantity { get; set; }
        public Nullable<int> FactQuantity { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public System.Guid ReturnOrderID { get; set; }
        public string ReturnOrderCode { get; set; }
    }
}
