//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vm_Warehouse
    {
        public System.Guid WarehouseID { get; set; }
        public System.Guid CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public bool IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactMobilePhone { get; set; }
        public string WarehousePhone { get; set; }
        public string WarehouseAddress { get; set; }
        public Nullable<int> WarehouseCityID { get; set; }
        public string WarehouseCityName { get; set; }
        public string WarehouseTypeCode { get; set; }
        public string WarehouseTypeName { get; set; }
    }
}
