//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_interface2oms_2_21_SalesOrder
    {
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string HHName { get; set; }
        public string HHPhone { get; set; }
        public string HHAddress { get; set; }
        public string SalesOrderCode { get; set; }
        public Nullable<int> SalesOrderStatusCode { get; set; }
        public string SalesOrderStatusName { get; set; }
        public string ContractCode { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> MaterialType { get; set; }
        public string MaterialTypeName { get; set; }
        public string SubmitSource { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public string ProjectTypeName { get; set; }
        public Nullable<int> DeliveryMode { get; set; }
        public string DeliveryModeName { get; set; }
        public string HHContacts { get; set; }
        public string HHContactPhone { get; set; }
        public Nullable<System.DateTime> ExpetDeliveryDate { get; set; }
        public System.Guid SalesOrderID { get; set; }
    }
}
