//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_ts_SubFunc
    {
        public string SubFuncCode { get; set; }
        public string FuncCode { get; set; }
        public string GroupCode { get; set; }
        public string SubFuncName { get; set; }
        public Nullable<int> DisNo { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public bool is_bgc { get; set; }
    }
}
