//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_DeliveryOrderItem
    {
        public System.Guid DeliveryOrderItemID { get; set; }
        public System.Guid DeliveryOrderID { get; set; }
        public Nullable<System.Guid> SalesOrderItemID { get; set; }
        public int DeliveryQuantity { get; set; }
        public string Batch { get; set; }
        public string InventoryTypeCode { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> FinalQuantity { get; set; }
        public string Color { get; set; }
        public string Unit { get; set; }
        public Nullable<int> OOSQuantity { get; set; }
        public string MaterialName { get; set; }
        public string MaterialCode { get; set; }
        public string Model { get; set; }
        public string MaterialTypeName { get; set; }
        public Nullable<System.Guid> MaterialID { get; set; }
        public string InventoryTypeName { get; set; }
        public bool IsInPaArchive { get; set; }
        public string DeliveryOrderCode { get; set; }
        public Nullable<int> DeliveryOrderStatusCode { get; set; }
        public string DeliveryOrderStatusName { get; set; }
    }
}
