//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_va_Inventory
    {
        public System.Guid InventoryDailyID { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.DateTime ArchiveDate { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public System.Guid WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public System.Guid MaterialID { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string BarCode { get; set; }
        public string Model { get; set; }
        public string Standard { get; set; }
        public string Unit { get; set; }
        public string InventoryTypeCode { get; set; }
        public string InventoryTypeName { get; set; }
        public string Batch { get; set; }
        public Nullable<int> ReserveQuantity { get; set; }
        public Nullable<int> WarningQuantity { get; set; }
        public int Quantity_First { get; set; }
        public Nullable<decimal> Amount_First { get; set; }
        public Nullable<int> Quantity_In { get; set; }
        public Nullable<decimal> Amount_In { get; set; }
        public Nullable<int> Quantity_Out { get; set; }
        public Nullable<decimal> Amount_Out { get; set; }
        public int Quantity_End { get; set; }
        public Nullable<decimal> Amount_End { get; set; }
        public System.Guid SupplierID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public decimal SupplyTaxPrice { get; set; }
        public decimal SupplyNoTaxPrice { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public string Kind { get; set; }
        public string SubKind { get; set; }
        public string Kind_3rd { get; set; }
    }
}
