//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_ReturnOrder_SalesOrderInfo
    {
        public System.Guid SalesOrderID { get; set; }
        public string SalesOrderCode { get; set; }
        public Nullable<int> SalesOrderStatusCode { get; set; }
        public string SalesOrderStatusName { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public System.Guid WarehouseID { get; set; }
        public Nullable<int> SalesOrderMaterialType { get; set; }
        public string SalesOrderMaterialTypeName { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public string HHName { get; set; }
        public string HHPhone { get; set; }
        public string HHMobilePhone { get; set; }
        public string HHAddress { get; set; }
        public string HHContacts { get; set; }
        public string HHContactPhone { get; set; }
        public string HHProvince { get; set; }
        public string HHCity { get; set; }
        public string HHDistrict { get; set; }
    }
}
