//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_Purchase_SelectPurchaseOrder
    {
        public System.Guid PurchaseOrderID { get; set; }
        public System.Guid CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string PurchaseOrder { get; set; }
        public int PurchaseStatusCode { get; set; }
        public string PurchaseStatusName { get; set; }
        public string PurchaseTypeCode { get; set; }
        public string PurchaseTypeName { get; set; }
        public Nullable<System.Guid> Submitter { get; set; }
        public string SubmitterName { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string SubmitterPhone { get; set; }
        public Nullable<System.DateTime> ExpetDeliveryDate { get; set; }
        public Nullable<System.Guid> WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string Consignee { get; set; }
        public string ConsigneePhone { get; set; }
        public string ConsigneeAddress { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public string ContractCode { get; set; }
    }
}
