//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_tm_WarehouseWorker
    {
        public System.Guid WarehouseWorkerID { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> WarehouseID { get; set; }
        public Nullable<System.Guid> OperatorID { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public bool IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
