//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_tt_PurchaseOrder
    {
        public System.Guid PurchaseOrderID { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public string PurchaseOrder { get; set; }
        public int PurchaseStatusCode { get; set; }
        public string PurchaseTypeCode { get; set; }
        public Nullable<System.Guid> Submitter { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string SubmitterPhone { get; set; }
        public Nullable<System.DateTime> ExpetDeliveryDate { get; set; }
        public string RejectReason { get; set; }
        public Nullable<System.Guid> WarehouseID { get; set; }
        public string HHName { get; set; }
        public string ContractCode { get; set; }
        public Nullable<int> ConsigneeCityID { get; set; }
        public string Consignee { get; set; }
        public string ConsigneePhone { get; set; }
        public string ConsigneeAddress { get; set; }
        public string Memo { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public Nullable<bool> ReviewStandard { get; set; }
        public Nullable<System.Guid> CurrentReviewRuleItemID { get; set; }
        public Nullable<System.Guid> CurrentReviewSubmiter { get; set; }
        public Nullable<int> CurrentReviewStatusCode { get; set; }
        public Nullable<System.DateTime> CurrentReviewBeginTime { get; set; }
        public Nullable<bool> IsAbort { get; set; }
        public Nullable<System.Guid> AbortBy { get; set; }
        public Nullable<bool> IsopenData { get; set; }
        public Nullable<System.Guid> openPurchaseOrderID { get; set; }
    }
}
