//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_interface2oms_2_21_SalesOrderItem
    {
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Unit { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public string DetailStatusName { get; set; }
        public Nullable<int> WMSStatus { get; set; }
        public string WMSStatusName { get; set; }
        public Nullable<int> DeliveryQuantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public Nullable<decimal> StandardValue { get; set; }
        public string LocationDetail { get; set; }
        public System.Guid SalesOrderID { get; set; }
        public string SalesOrderCode { get; set; }
    }
}
