//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vx_xhelper_sys_Globe
    {
        public Nullable<System.Guid> NewGUID { get; set; }
        public System.DateTime NowDate { get; set; }
        public Nullable<double> RandNum { get; set; }
        public Nullable<System.DateTime> MinDateTime { get; set; }
        public Nullable<System.DateTime> MaxDateTime { get; set; }
        public Nullable<System.Guid> EmptyGuid { get; set; }
        public string EmptyXML { get; set; }
        public string cons_success { get; set; }
        public string cons_failure { get; set; }
        public string cons_response { get; set; }
    }
}
