//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_tm_Material
    {
        public System.Guid MaterialID { get; set; }
        public System.Guid CompanyID { get; set; }
        public int MaterialType { get; set; }
        public int SupplyType { get; set; }
        public Nullable<int> TransMode_default { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string BarCode { get; set; }
        public string Kind { get; set; }
        public string SubKind { get; set; }
        public string Kind_3rd { get; set; }
        public string Brand { get; set; }
        public string SubBrand { get; set; }
        public string Color { get; set; }
        public decimal SalesPrice { get; set; }
        public decimal ConvertRate { get; set; }
        public decimal DamageRate { get; set; }
        public decimal ProessingFee { get; set; }
        public decimal InstalltionFee { get; set; }
        public decimal PaintFee { get; set; }
        public string Unit { get; set; }
        public string Standard { get; set; }
        public string Model { get; set; }
        public int Length { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public decimal Volume { get; set; }
        public decimal Weight { get; set; }
        public int TransFeeSettlementsMode { get; set; }
        public int MinPurchaseQuantity { get; set; }
        public int ReserveQuantity { get; set; }
        public int WarningQuantity { get; set; }
        public int MinDeliveryQuantity { get; set; }
        public int HouseholdValue { get; set; }
        public Nullable<System.DateTime> HouseholdValue_CalcDate { get; set; }
        public int Supplier_SignVerifyCostDays { get; set; }
        public int Supplier_ManufactureCostDays { get; set; }
        public int Supplier_TransCostDays { get; set; }
        public string Buyer { get; set; }
        public int BestBefore { get; set; }
        public int CloseBest { get; set; }
        public string UseTo { get; set; }
        public string MaterialBy { get; set; }
        public bool DeliveryByPreviousBatch { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public bool IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<bool> StopUse { get; set; }
        public Nullable<System.Guid> ParentMaterialID { get; set; }
        public Nullable<bool> IsGift { get; set; }
        public Nullable<int> Quantity_Total_Purchase { get; set; }
        public Nullable<int> Quantity_Total_Sales { get; set; }
        public Nullable<int> Quantity_Purchase_Intransit { get; set; }
        public Nullable<int> Quantity_Purchase_ReadyTransit { get; set; }
        public Nullable<int> Quantity_Purchase_Adviseable { get; set; }
        public Nullable<int> Quantity_Purchase_NotWarehoused { get; set; }
        public Nullable<int> Quantity_Sales_BeginWork_NotDelivery { get; set; }
        public Nullable<int> Quantity_Sales_ReadyWork_NotDelivery { get; set; }
        public Nullable<int> Quantity_Sales_NeedPurchase_NotDelivery { get; set; }
        public string bak_materialbode_180301 { get; set; }
        public string o_skuId { get; set; }
        public string o_skuCode { get; set; }
        public Nullable<System.DateTime> lastest_date_poio_in { get; set; }
        public Nullable<System.DateTime> lastest_date_do_out { get; set; }
        public Nullable<System.DateTime> vss_sync_date { get; set; }
        public string Original_producer { get; set; }
        public Nullable<System.DateTime> sync_vk_date { get; set; }
    }
}
