//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_tm_Operator
    {
        public System.Guid OperatorID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public string OperatorCode { get; set; }
        public string OperatorName { get; set; }
        public Nullable<System.Guid> OperatorRoleID { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> LoginErrorTimes { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public bool IsSupplier { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public Nullable<bool> top_secret_viewer { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public Nullable<bool> is_bgc { get; set; }
    }
}
