//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vl_InterfaceFeedBack_DeliveryOrderLog
    {
        public System.Guid CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public System.Guid DeliveryOrderID { get; set; }
        public Nullable<System.DateTime> FactDeliveryDate { get; set; }
        public string SalesOrderCode { get; set; }
        public string ParentSalesOrderCode { get; set; }
        public Nullable<int> SyncVssNum_Delivery { get; set; }
        public string DeliveryOrderCode { get; set; }
        public System.Guid SalesOrderID { get; set; }
    }
}
