//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_open_tl_Request
    {
        public System.Guid RequestID { get; set; }
        public string APPCode { get; set; }
        public string OpenAPPCode { get; set; }
        public Nullable<bool> IO { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string TokenBy { get; set; }
        public string Secret { get; set; }
        public string Url { get; set; }
        public string Call { get; set; }
        public string Body { get; set; }
        public string Response { get; set; }
        public Nullable<int> ProcessStatusCode { get; set; }
        public Nullable<int> ProcessCount { get; set; }
        public string ProcessResult { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsObsoleted { get; set; }
        public string BizDataIdentity { get; set; }
        public Nullable<bool> Success { get; set; }
    }
}
