//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_Purchase_SalesOrderItem
    {
        public string ContractCode { get; set; }
        public string SalesOrderCode { get; set; }
        public System.Guid SalesOrderItemID { get; set; }
        public System.Guid CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public System.Guid SalesOrderID { get; set; }
        public System.Guid MaterialID { get; set; }
        public string MaterialCode { get; set; }
        public string BarCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> MaterialType { get; set; }
        public string MaterialTypeName { get; set; }
        public Nullable<int> SupplyType { get; set; }
        public string SupplyTypeName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ConversionQuantity { get; set; }
        public Nullable<int> ExpectDamageQuantity { get; set; }
        public int SaleableQuantity { get; set; }
        public Nullable<int> DeliveryQuantity { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string StandardDetail { get; set; }
        public Nullable<System.Guid> SalesOrder_SupplierID { get; set; }
        public System.Guid Price_SupplierID { get; set; }
        public string Price_SupplierCode { get; set; }
        public string Price_SupplierName { get; set; }
        public Nullable<int> OOSQuantity { get; set; }
        public string DrawingsURL { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public Nullable<bool> ReviewFinishItem { get; set; }
        public decimal SupplyTaxPrice { get; set; }
        public int TransMode { get; set; }
        public string TransModeName { get; set; }
        public Nullable<System.Guid> PurchaseOrderItemID { get; set; }
        public Nullable<int> FinalQuantity { get; set; }
    }
}
