//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_PurchaseOrderItem
    {
        public System.Guid PurchaseOrderItemID { get; set; }
        public System.Guid CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public System.Guid PurchaseOrderID { get; set; }
        public System.Guid MaterialID { get; set; }
        public Nullable<System.Guid> ParentMaterialID { get; set; }
        public string MaterialName { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string Standard { get; set; }
        public string MaterialCode { get; set; }
        public Nullable<int> MaterialType { get; set; }
        public string MaterialTypeName { get; set; }
        public Nullable<int> SupplyType { get; set; }
        public string SupplyTypeName { get; set; }
        public string BarCode { get; set; }
        public Nullable<bool> IsGift { get; set; }
        public Nullable<int> MinPurchaseQuantity { get; set; }
        public string Unit { get; set; }
        public Nullable<System.Guid> SalesOrderItemID { get; set; }
        public int SubmitQuantity { get; set; }
        public int AdjustQuantity { get; set; }
        public int ExpectDeliveryQuantity { get; set; }
        public int WarehousedQuantity { get; set; }
        public int BalanceQuantity { get; set; }
        public int SettlementsQuantity { get; set; }
        public int TransMode { get; set; }
        public string TransModeName { get; set; }
        public decimal SupplyPrice { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public string StandardDetail { get; set; }
        public Nullable<decimal> StandardValue { get; set; }
        public decimal TransPrice_Land { get; set; }
        public decimal TransPrice_Air { get; set; }
        public decimal TransPrice_Sea { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public string PurchaseTypeCode { get; set; }
        public Nullable<int> PurchaseStatusCode { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string SalesOrderCode { get; set; }
        public string ContractCode { get; set; }
        public string HHAddress { get; set; }
        public bool ReviewStandard { get; set; }
        public string DrawingsURL { get; set; }
        public string LocationDetail { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string DrawingsURLName { get; set; }
        public string PurchaseOrder { get; set; }
        public Nullable<int> Quantity_Purchase_Adviseable { get; set; }
        public Nullable<int> Quantity_Purchase_Intransit { get; set; }
        public Nullable<int> Quantity_Purchase_NotWarehoused { get; set; }
        public Nullable<int> Quantity_Purchase_ReadyTransit { get; set; }
        public Nullable<System.Guid> openPurchaseOrderItemID { get; set; }
    }
}
