//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vm_tms_City
    {
        public int CityID { get; set; }
        public string LeverCode { get; set; }
        public string City { get; set; }
        public Nullable<int> ParentCityID { get; set; }
        public string CityAllName { get; set; }
        public string Phone { get; set; }
        public string PostNo { get; set; }
        public string ChinaSpell { get; set; }
        public string ChinaSpellAll { get; set; }
        public string PinYin { get; set; }
        public Nullable<double> CityCode { get; set; }
    }
}
