//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vl_InterfaceFeedback_RejectReturnLog
    {
        public System.Guid CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public System.Guid ReturnOrderID { get; set; }
        public string ReturnOrderCode { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public string RejectReason { get; set; }
        public string Rejecter { get; set; }
        public Nullable<int> SyncVssNum_Rejecter { get; set; }
    }
}
