//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_interface2oms_2_24_ReturnOrder
    {
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string ReturnOrderCode { get; set; }
        public string ReturnOrderStatusCode { get; set; }
        public string ReturnOrderStatusName { get; set; }
        public string SalesOrderCode { get; set; }
        public bool Recaption { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string Returner { get; set; }
        public string ReturnerPhone { get; set; }
        public string ReturnerAddress { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> WarehousedDate { get; set; }
        public Nullable<System.Guid> Rejecter { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public string RejectReason { get; set; }
        public string HHName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ReturnModeCode { get; set; }
        public string ReturnModeName { get; set; }
        public System.Guid ReturnOrderID { get; set; }
        public string ContractCode { get; set; }
    }
}
