//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_vt_ReturnOrder
    {
        public System.Guid ReturnOrderID { get; set; }
        public System.Guid CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string ReturnOrderCode { get; set; }
        public string ReturnOrderStatusCode { get; set; }
        public string ReturnOrderStatusName { get; set; }
        public System.Guid SalesOrderID { get; set; }
        public string SalesOrderCode { get; set; }
        public System.Guid WarehouseID { get; set; }
        public bool Recaption { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string Returner { get; set; }
        public string ReturnerPhone { get; set; }
        public string ReturnerAddress { get; set; }
        public Nullable<int> ReturnerCityID { get; set; }
        public string ReturnerCity { get; set; }
        public string Consignee { get; set; }
        public string ConsigneePhone { get; set; }
        public string ConsigneeAddress { get; set; }
        public Nullable<int> ConsigneeCityID { get; set; }
        public string ConsigneeCity { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> WarehousedDate { get; set; }
        public Nullable<System.Guid> Rejecter { get; set; }
        public string OperatorCode { get; set; }
        public string OperatorName { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public string RejectReason { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public string HHName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public string OwnerShop { get; set; }
        public Nullable<int> ReturnModeCode { get; set; }
        public string ReturnModeName { get; set; }
    }
}
