//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_tt_WarehouseIO
    {
        public System.Guid WarehouseIOID { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid WarehouseID { get; set; }
        public string WarehouseIOCode { get; set; }
        public string WarehouseIOTypeCode { get; set; }
        public string WarehouseIOStatusCode { get; set; }
        public Nullable<System.Guid> Verifyer { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public string RejectReason { get; set; }
        public string LinkDataTypeCode { get; set; }
        public Nullable<System.Guid> LinkDataID { get; set; }
        public Nullable<int> DeliveryMode { get; set; }
        public Nullable<System.DateTime> ExpetDeliveryDate { get; set; }
        public Nullable<System.DateTime> WarehouseConfirmDate { get; set; }
        public Nullable<System.Guid> PurchaseOrderID { get; set; }
        public string Consignee { get; set; }
        public string ConsigneePhone { get; set; }
        public string ConsigneeAddress { get; set; }
        public Nullable<int> ConsigneeCityID { get; set; }
        public string Shipper { get; set; }
        public string ShipperPhone { get; set; }
        public string ShipperAddress { get; set; }
        public Nullable<int> ShipperCityID { get; set; }
        public Nullable<bool> ShipperDelivery { get; set; }
        public Nullable<System.DateTime> ShipperDeliveryDate { get; set; }
        public bool Recaption { get; set; }
        public string Memo { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<bool> IsBalance { get; set; }
        public string ExpectionMemo { get; set; }
        public string MakingOrderNo { get; set; }
        public Nullable<bool> WaitSyncWMS { get; set; }
        public string DrawingsURL { get; set; }
        public Nullable<System.Guid> CurrentReviewRuleItemID { get; set; }
        public Nullable<System.Guid> CurrentReviewSubmiter { get; set; }
        public Nullable<int> CurrentReviewStatusCode { get; set; }
        public Nullable<System.DateTime> CurrentReviewBeginTime { get; set; }
        public Nullable<bool> IsopenData { get; set; }
        public Nullable<System.Guid> openShoppingOrderID { get; set; }
    }
}
