//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_open_vt_ShipmentOrder
    {
        public System.Guid openShipmentOrderID { get; set; }
        public Nullable<System.Guid> openShoppingOrderID { get; set; }
        public System.Guid APPID { get; set; }
        public string o_mainOrderId { get; set; }
        public Nullable<System.Guid> o_erpOrderId { get; set; }
        public string o_shoppingOrderId { get; set; }
        public string o_shipmentId { get; set; }
        public string o_deliverNo { get; set; }
        public string o_deliverWay { get; set; }
        public string o_carrier { get; set; }
        public Nullable<System.DateTime> o_sendAt { get; set; }
        public Nullable<System.DateTime> o_planArriveAt { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> openShipmentOrderStatusCode { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> o_time { get; set; }
        public string openShipmentOrderStatusName { get; set; }
        public Nullable<System.DateTime> WarehouseConfirmDate { get; set; }
        public Nullable<System.Guid> openPurchaseOrderID { get; set; }
        public string PurchaseOrder { get; set; }
        public string WarehouseIOCode { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string task_info { get; set; }
    }
}
