//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class oms_tt_BillOrderItem
    {
        public System.Guid BillOrderItemID { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid BillOrderID { get; set; }
        public System.Guid WarehouseIOID { get; set; }
        public Nullable<System.Guid> WarehouseIOItemID { get; set; }
        public System.Guid MaterialID { get; set; }
        public int TransMode { get; set; }
        public decimal SupplyPrice { get; set; }
        public int BillingQuantity { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsObsoleted { get; set; }
    }
}
